version: '3.8'

services:
  masterinvoice:
    image: masterinvoice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - sqldata
    networks:
      - backend

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=numsey#1234
      - ACCEPT_EULA=Y
    volumes:
      - C:\Dados\volumes\mssql:/var/opt/mssql/data
    ports:
      - "1433:1433"
    expose:
      - '1433'
    networks:
      - backend

networks:
  backend:
    driver: bridge
